### ISSUE TITLE
Announcing crossbeam-epoch 0.1.0?

### ISSUE THREAD

**Issue by jeehoonkang** [crossbeam-rs/crossbeam-epoch#14]
It seems crossbeam-epoch is comparable to both the original crossbeam and coco in terms of features.  For example, I could successfully port rsdb, which was based on coco, to crossbeam-epoch: https://github.com/jeehoonkang/rsdb/tree/crossbeam-epoch  Also, its performance seems not bad compared to the two precursors.

So I wonder if (1) we want to announce the initial 0.1.0 release of the core of new crossbeam, and (2) when.  Personally, I want to announce it after both https://github.com/crossbeam-rs/rfcs/pull/9 and https://github.com/crossbeam-rs/crossbeam-epoch/pull/13 are somehow resolved.

What do you think?

**Comment by ghost** [comment]
Yesterday I noticed segmentation faults and would like to investigate what went wrong before releasing 0.1.0.

I think as far as features go, we're getting ready for an early release, but I'm still feeling a bit uneasy without at least some basic sanitization tests (similar to the tests I wrote for `coco`).

**Comment by jeehoonkang** [comment]
I'd like to enumerate the release blockers.

- We need tests (cf. #17).

- @stjepang Can you reproduce the segfault for the current master?

- I guess @Vtec234 wants to add benchmark before we publish crossbeam-epoch 0.1.0.  But it's unclear which benchmark we should evaluate before releasing 0.1.0.

**Comment by jeehoonkang** [comment]
How about writing up a post for advertising `crossbeam-epoch` for wider audience (e.g. reddit, lobste.rs) at the time of 0.1.0 release?

cf. the write-up will close https://github.com/crossbeam-rs/rfcs/issues/7

**Comment by ghost** [comment]
@jeehoonkang I'll submit a PR that adds some benchmarks soon (today or tomorrow).

Regarding your comments on backward compatibility, I think it's simply inevitable that we'll break compatibility multiple times within the next several months. This is normal for such a young and complicated project. :)

I'd prefer to release a new version soon so that other subprojects (`crossbeam-deque` and `crossbeam-channel`) can start relying on it. We have to kick the ball rolling at some point.

The project seems to be in a fairly solid state now. I've just run tests on my Raspberry Pi (ARM v7) and everything seems to be working just fine. What do you think - after adding benchmarks, can we release a 0.1.0 so that `crossbeam-epoch` can be used as a dependency?

We don't have to publicise this release yet, but once things settle down, we'll definitely do it.

**Comment by jeehoonkang** [comment]
I'd like to release 0.1.0 after resolving the following PRs and issues: #35 (#30), #34, #33, #32

They are relatively small, so I think we merge them very soon.  Then let's release 0.1.0, finally!
