### ISSUE TITLE
Should Atomic implement Clone?

### ISSUE THREAD

**Issue by ghost** [crossbeam-rs/crossbeam-epoch#23]
I was implementing a simple Bw-Tree and had a vector of the following type:
```rust
Vec<(K, Atomic<Page<K, V>>)>
```

This vector had to be cloned, but it didn't implement `Clone` because `Atomic<T>` doesn't implement it. So I have to manually go through each element of the vector, load the `Atomic<Page<K, V>>` and then create a clone myself. I should also note that those `Atomic`s never change - they are in fact immutable.

We have this pattern of immutable `Atomic`s actually coming up pretty often. For example, in a lock-free stack nodes are defined as:

```rust
struct Node<T> {
    value: ManuallyDrop<T>,
    next: Atomic<Node<T>>,
}
```

The `next` field becomes immutable once we push the new node onto the stack. This is why loading `next` pointers using `Relaxed` is okay.

Is it a reasonable idea to implement `Clone` for `Atomic<T>`? If so, how would we implement it? Would we load the value using `Relaxed` or maybe `SeqCst`?

**Comment by jeehoonkang** [comment]
I think it's reasonable to implement `Clone` for `Atomic<T>`.  As you said, it's just an immutable pointer to a shared object with interior mutability.  Also I think we don't need an RFC for this change.


> The `next` field becomes immutable once we push the new node onto the stack. This is why loading `next` pointers using `Relaxed` is okay.

Hmm, if I'm understanding your sentence correctly, I disagree with you here..  In order to safely access the data in the next block, loading from the `next` pointer should be ~~`Release`~~ `Acquire`.

**Comment by arthurprs** [comment]
> Hmm, if I'm understanding your sentence correctly, I disagree with you here.. In order to safely access the data in the next block, loading from the next pointer should be Release.

After the node is created, wouldn't `stack.top.cas(old_top, new_top, XXXRelease)` be enough?

**Comment by jeehoonkang** [comment]
@arthurprs Sorry!  I updated the comment.  I meant loading from `next` should be `Acquire`.

**Comment by ghost** [comment]
> I think it's reasonable to implement `Clone` for `Atomic<T>`. As you said, it's just an immutable pointer to a shared object with interior mutability.

Not disagreeing with you, but the reason why I'm feeling slightly uneasy about implementing `Clone` is that there isn't much precedent. In particular, `AtomicUsize` and `Mutex` don't implement `Clone`, and probably for a good reason. Interestingly, `Cell` and `RefCell` also provide interior mutability but do implement `Clone`.

> I meant loading from `next` should be `Acquire`.

Well, it depends whose burden it is to synchronize things. If you're cloning an immutable `Atomic<T>`, the store that happened to it should already be synchronized. Take a look at `TreiberStack` for an example, where we [load `next` using `Relaxed`](https://github.com/crossbeam-rs/crossbeam/blob/master/src/sync/treiber_stack.rs#L60).

I believe we're okay with using `Relaxed` load for cloning. But I'd be fine with the inverse philosophy: Let's use `SeqCst` *just in case* (to prevent accidental bugs), and if someone really needs faster `Clone`, they can implement it themselves.

**Comment by jeehoonkang** [comment]
> there isn't much precedent.

... Yes, I'm curious why `std::sync::Mutex<T>` doesn't implement `clone()`.  It's current defined as (roughly) a pair of `Box<StaticMutex>` and `UnsafeCell<T>`, which naturally doesn't allow `clone()`.  However, it could have been defined as `Arc<(UnsafeCell<T>, StaticMutex)>`, which will admit a natural implementation of `clone()` (i.e. that of `Arc`), while supporting the existing operations.  Furthermore, considering that `Mutex<T>` is almost always used as `Arc<Mutex<T>>`, there will be one less indirection in accessing the underlying data.

Going back to the main topic, I agree with you in that we need to know why Rust `std`'s `AtomicUSize` and `Mutex` doesn't implement `clone()`.  But I'm inclined to supporting `Atomic::clone()`, because it's useful for your use case.

> it depends whose burden it is to synchronize things.

@stjepang I agree with you.  Since I don't expect any synchronization to happen in `clone()`, I'm for using `Relaxed` rather than `SeqCst`.

**Comment by ghost** [comment]
We've implemented this. closing.
