### ISSUE TITLE
Supporting Rust 1.12 for Rayon

### ISSUE THREAD

**Issue by jeehoonkang** [crossbeam-rs/crossbeam-epoch#57]
In order to use Crossbeam in Rayon, we need to support Rust 1.12.  More discussions are in: https://github.com/rayon-rs/rayon/pull/480 .

I hope it is the only remaining blocker for Rayon.

**Comment by Vtec234** [comment]
Supporting this in crossbeam-utils turns out to be unnecessarily annoying, because the usage of `#[repr(align(n))]` syntax under the `nightly` feature breaks rustc 1.12, which does not recognise that syntax. Rustc also tries to parse the file even when the nightly implementation is put into a separate file, with that file's `mod` statement guarded by `feature = "nightly"`. The only solution I see at the moment is to support two versions, i.e. first publish 0.3.0 without nightly support, but working for 1.12 and then 0.4.0 for more recent versions. If anyone figures out how to conditionally compile a file, that would avoid the version split.

**Comment by joshlf** [comment]
@Vtec234 perhaps you could have the `#[repr(align(n))]` syntax generated by a macro that is only compiled on nightly? The hope being that parsing the macro definition will succeed even if the parsing the code generated by invoking that macro wouldn't.

**Comment by Vtec234** [comment]
@joshlf That actually worked, thanks!

**Comment by joshlf** [comment]
Awesome, np!

**Comment by jeehoonkang** [comment]
https://github.com/Gilnaa/memoffset/pull/2 I just asked the maintainer of `memoffset` to support Rust 1.12.1.

**Comment by jeehoonkang** [comment]
We dedicated `crossbeam-epoch` 0.3.0 for Rust 1.13, and I think it's the best we can do for now: supporting Rust 1.12.1 will require a huge effort.  Closing it as won't fix!
