### ISSUE TITLE
Should `internal::Local` be `Sync`?

### ISSUE THREAD

**Issue by Thomasdezeeuw** [crossbeam-rs/crossbeam-epoch#65]
Currently the `internal::Local` struct is marked as `Sync`. However it uses `Cell` for the guard and handle counts, which is not `Sync`, only `Send`. I don't think it safe to mark `internal::Local` as `Sync`, but only as `Send` (given that the other field are ok to be `Send`).

**Comment by Amanieu** [comment]
First of all, `Local` is an internal type which is never publicly exposed, so it doesn't really matter if we get `Sync` wrong as long as we are careful about how we access it internally.

Secondly, parts of a `Local` are accessed from multiple threads, but only the thread-safe parts. So it is semi-Sync. This is why this whole part of the code is full of `unsafe`.

**Comment by Thomasdezeeuw** [comment]
I know `Local` is internal, is it located the `internal` module. However I don't think that makes it ok to get `Sync` wrong.

Furthermore I'm fairly sure your second point is incorrect. Consider the following (peusdo) code:

```rust
use epoch::{Collector}

// On thread 1.
collector = Collector::new();
let handle = collector::handle();
let second_handle = handle.clone();

// Send `second_handle` accross thread (it is `Send` after all).
// On thread 2.
drop(second_handle);

// On thread 1.
drop(handle);
```

In the `Drop` implementation of `Handle` it calls `Local::release_handle`, which does access `handle_count`.

**Comment by Amanieu** [comment]
Ah this does seem like a bug. Since `Handle` is `Send`, `Handle::clone` should create a new `Local`, not increment the reference count for the current handle.

@stjepang thought?

**Comment by ghost** [comment]
This is a bug because `Handle` is not supposed to implement `Send` nor `Sync`. 

The fix is to simply delete line `unsafe impl Send for Handle {}`.

Both `Collector` and `Handle` refer to reference-counted objects. Cloning simply gives you another reference to the same thing. `Collector` is internally just an `Arc<Global>`, while `Handle` is just an `Rc<Local>` (we don't *actually* use `Rc`, but we do imitate it with `handle_count`).

A `Handle` is always tied to the current thread and cannot escape it. Once created, `Handle` cannot be sent to another thread, but you can create clones of it for convenience.

--------------

For some historical context, we previously discussed if we should change the behavior of `Handle` so that cloning registers a brand new handle and make `Handle` sendable to other threads.

The problem with this design arises when you start pinning. Consider this:

```rust
let collector = Collector::new();

let handle = collector.handle();
let guard1 = handle.pin();

// `handle` is moved into a new thread.
thread::spawn(move || {
    let guard2 = handle.pin();
});
```

There is nothing inherently wrong with this piece of code - `guard1` and `guard2` are keeping the same handle pinned, and that's okay. However, if we were to allow this, then pinning would have to perform atomic operations. For example, `pin_count` would have to be of type `AtomicUsize` rather than `Cell<Wrapping<usize>>`, which would make pinning slower.

I don't remember if there where any other complications, but the benchmark numbers for pinning under this design were not good. In the end, we decided to simply prohibit sending `Handle`s to other threads.

A possible alternative was to make sending a `Handle` to another thread an unsafe thing to do *somehow*, but then the API felt non-ideal so we gave up on that idea, too.

**Comment by Thomasdezeeuw** [comment]
The example I gave would indeed be fixed if `Handle` didn't implement `Send`.

However that doesn't really fix the problem that `internal::Local` really shouldn't implement `Sync`. If `Local` is already fixed to a thread, maybe a better solution exists for that without `Local` implementing `Sync`. Or alternatively don't use `Cell` in `Local` at all.
